language: perl
matrix:
  include:
  - perl: "5.16"
    dist: trusty
  - perl: "5.22"
  - perl: "5.26"
  - perl: "5.30"

cache:
  directories:
    - $HOME/perl5

env:
  global:
    - HARNESS_OPTIONS=j5

sudo: false
notifications:
  email: false

install:
  - cpanm -n --quiet --installdeps --with-develop .

after_success:
  - cover -test -report coveralls
  - cover -test -report kritika
