language: perl

perl:
  - "5.16"
  - "5.22"
  - "5.26"
  - "5.30"

cache:
  directories:
    - $HOME/perl5

env:
  global:
    - HARNESS_OPTIONS=j5

sudo: false
notifications:
  email: false

install:
  - cpanm -n --quiet --installdeps --with-develop .

after_success:
  - cover -test -report coveralls
  - cover -test -report kritika
